name: Deploy to SFTP Server

on:
  push:
    branches:
      - master  # Adjust this branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm@6.27.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Rename dist folder
        run: mv dist signature

      - name: Set up SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./dist
          server-dir: ~/html/signature-test/
